name: maproom
dependencies:
- ca-certificates=2016.8.2=3
- certifi=2016.8.2=py27_0
- configobj=5.0.6=py27_0
- coverage=4.2=py27_0
- curl=7.49.1=0
- cython=0.24.1=py27_0
- docutils=0.12=py27_0
- expat=2.1.0=1
- freetype=2.6.3=1
- freexl=1.0.2=1
- gdal=2.1.1=np111py27_1
- geos=3.4.2=2
- giflib=5.1.2=1
- hdf4=4.2.11=4
- hdf5=1.8.17=2
- icu=56.1=4
- jpeg=9b=0
- json-c=0.12=0
- kealib=1.4.6=3
- libdap4=3.18.0=2
- libiconv=1.14=3
- libnetcdf=4.4.1=0
- libpng=1.6.23=0
- libspatialite=4.3.0a=9
- libtiff=4.0.6=6
- libuuid=1.0.3=1
- libxml2=2.9.3=9
- markdown=2.6.6=py27_0
- netcdf4=1.2.4=np111py27_2
- nomkl=1.0=0
- numpy=1.11.1=py27_nomkl_0
- openjpeg=2.1.0=6
- openssl=1.0.2h=2
- pillow=3.3.0=py27_0
- pip=8.1.2=py27_0
- postgresql=9.5.3=2
- proj.4=4.9.2=0
- py=1.4.31=py27_0
- pycrypto=2.6.1=py27_4
- pyinstaller=3.2=py27_2
- pyopengl=3.1.1a1=np111py27_0
- pyopengl-accelerate=3.1.1a1=np111py27_0
- pyparsing=2.1.4=py27_0
- pyproj=1.9.5.1=py27_0
- pytest=2.9.2=py27_0
- pytest-cov=2.3.0=py27_0
- python=2.7.12=1
- python.app=1.2=py27_4
- pyugrid=0.2.2=py27_0
- readline=6.2=2
- reportlab=3.3.0=py27_0
- requests=2.10.0=py27_0
- setuptools=19.2=py27_0
- shapely=1.5.16=np111py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=1
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- wxpython=3.0.2.0=py27_0
- xerces-c=3.1.4=2
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - atrcopy==3.1.0
  - bson==0.4.3
  - jsonpickle==0.9.3
  - omnivore==0.13.2
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - wxpython-common==3.0.2.0

